### ISSUE TITLE
ACİL YARDIMINIZ GEREKLİ

### ISSUE THREAD

**Issue by yildiraykaraca** [salihseker/.Net-MVC-E-Commerce-e-Ticaret-Sitesi-Example#1]
HOCAM PROJENİZİ İNCELEMEK İSTİYORUM FAKAT VERİ TABANINI LOCAL OLARAK AYARLADIĞIMDA System.Data.Entity.Core.EntityCommandExecutionException HATASI VERİYOR VE VERİ TABANINA BAĞLANAMIYORUM.

**Comment by salihseker** [comment]
Merhabalar , öncelik olarak DB Backup ı github hesabına mevcut , bu backup ı yüklediten sonra gerekli yetkilendirme tanımlarını yapınız  db ye ulaşabilecek user lar v.s. security ayarlarınızı kontrol ediniz , daha sonrasında config ayarlarından conectonstring ayarınızı yapınız , win authentication değil user password şeklinde bağlanmayı deneyiniz , Entity Framwork kün kurulu olduğunu kontrol edniz Nuget tan indirin eğer eksik ise , oda olmadı Visual Studio ya Entity Framework 5.0 - Code First Reverse Engineering kurmayı deneyin  https://www.youtube.com/watch?v=UhJaEVQMxJ4 linkte anlatım ve download lnklei koymuşlar inceliyebilirsin. hatanın sebebini google da daha detaylı olarak araştırabilirsin ,kendi makinanda kaynaklı bir eksiklikten dolayı çalışmamaktadır  çok çeşitli sebepleri olabilir . Kolay gelsin.

**Comment by yildiraykaraca** [comment]
Hocam Ben projeyi açmayı başardım inceledim ve ben kendi yaptığım projemde sayfa yetkilerini identity ile koddan eklemiştim ders hocamız ise ben menüden yetki vericem diye tutturdu bu konuda acil yardım lazım projem hakkında.
